# Práctica 7 - SVM
> Daniel Armas Ramírez

> PhD Consuelo Varinia García Mendoza

## Lectura de data

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.multiclass import OneVsRestClassifier
from sklearn.svm import SVC

In [6]:
iris = datasets.load_iris()

> split data


In [7]:
X = iris.data
y = iris.target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

## Generando conjuntos One vs Rest

In [ ]:
def map_setosa(species):
    return 'Iris-setosa' if species == 'Iris-setosa' else 'No-setosa'

def map_versicolor(species):
    return 'Iris-versicolor' if species == 'Iris-versicolor' else 'No-versicolor'

def map_virginica(species):
    return 'Iris-virginica' if species == 'Iris-virginica' else 'No-virginica'

In [ ]:
df_setosa = df.copy()
df_setosa['species'] = df_setosa['species'].apply(map_setosa)

df_versicolor = df.copy()
df_versicolor['species'] = df_versicolor['species'].apply(map_versicolor)

df_virginica = df.copy()
df_virginica['species'] = df_virginica['species'].apply(map_virginica)

In [ ]:
model = OneVsRestClassifier(SVC(kernel='linear', probability=True))
model.fit(X_train, y_train)

classes = model.classes_

for i, classifier in enumerate(model.estimators_):
    support_vectors = classifier.support_vectors_
    support_indices = classifier.support_
    y_train_binary = (y_train == classes[i]).astype(int)
    indices_positive = np.where(y_train_binary == 1)[0]
    indices_negative = np.where(y_train_binary == 0)[0]

    support_vectors_positive = support_vectors[indices_positive]
    support_vectors_negative = support_vectors[indices_negative]

    average_support_vector_positive = np.mean(support_vectors_positive, axis=0)
    average_support_vector_negative = np.mean(support_vectors_negative, axis=0)

    average_support_vector = (average_support_vector_positive + average_support_vector_negative) / 2
    norm_support = np.linalg.norm(average_support_vector)

    norm_support_positive = np.linalg.norm(average_support_vector_positive)
    norm_support_negative = np.linalg.norm(average_support_vector_negative)


    print(f"Clasificador para Clase {classes[i]} :")

    print(f'Numéro de elementos pertenecientes a la clase {classes[i]}: {len(support_indices)}')

    print(f"X_train:\n{X_train}")
    print(f"y_train (binario):\n{y_train_binary}\n")

    print(f"Vector promedio de soporte para {classes[i]}: {average_support_vector_positive}")
    print(f"Vector promedio de soporte para no {classes[i]}: {average_support_vector_negative}")
    print(f"c: {average_support_vector}")

    print(f"Norma del vector promedio de soporte para {classes[i]}: {norm_support_positive}")
    print(f"Norma del vector promedio de soporte para no {classes[i]}: {norm_support_negative}")
    print(f"Norma del vector promedio de soporte: {norm_support}\n")

    print("-" * 100)

IndexError: index 6 is out of bounds for axis 0 with size 3

In [11]:
svm = SVC(kernel='linear', decision_function_shape='ovr', random_state=0, probability=True)
svm.fit(X_train, y_train)

def vector_norm(vector):
    return np.linalg.norm(vector)


for class_idx in range(len(iris.target_names)):
    support_vectors = svm.support_vectors_[svm.n_support_[:class_idx].sum():svm.n_support_[:class_idx + 1].sum()]

    non_support_vectors = np.delete(svm.support_vectors_, slice(svm.n_support_[:class_idx].sum(), svm.n_support_[:class_idx + 1].sum()), axis=0)

    mean_support_vector = np.mean(support_vectors, axis=0)
    norm_support_vector = vector_norm(mean_support_vector)

    mean_non_support_vector = np.mean(non_support_vectors, axis=0)
    norm_non_support_vector = vector_norm(mean_non_support_vector)

    hyperplane_vector = svm.coef_[class_idx]
    hyperplane_intercept = svm.intercept_[class_idx]

    print(f"Clase: {iris.target_names[class_idx]}")
    print(f"Número de instancias que pertenecen a la clase: {sum(y_train == class_idx)}")
    print(f"Vectores de soporte (clase): \n{support_vectors}")
    print(f"Vector promedio (clase): {mean_support_vector}")
    print(f"Norma del vector promedio (clase): {norm_support_vector}")
    print(f"Vectores de soporte (no clase): \n{non_support_vectors}")
    print(f"Vector promedio (no clase): {mean_non_support_vector}")
    print(f"Norma del vector promedio (no clase): {norm_non_support_vector}")
    print(f"Vector del hiperplano (coeficientes): {hyperplane_vector}")
    print(f"Intercepto del hiperplano: {hyperplane_intercept}")
    print("\n" + "-"*80 + "\n")

Clase: setosa
Número de instancias que pertenecen a la clase: 39
Vectores de soporte (clase): 
[[4.5 2.3 1.3 0.3]
 [5.1 3.3 1.7 0.5]]
Vector promedio (clase): [4.8 2.8 1.5 0.4]
Norma del vector promedio (clase): 5.769748694700662
Vectores de soporte (no clase): 
[[5.4 3.  4.5 1.5]
 [6.  2.7 5.1 1.6]
 [6.3 3.3 4.7 1.6]
 [6.1 3.  4.6 1.4]
 [6.9 3.1 4.9 1.5]
 [5.1 2.5 3.  1.1]
 [6.2 2.2 4.5 1.5]
 [5.7 2.8 4.5 1.3]
 [6.3 2.5 4.9 1.5]
 [6.7 3.  5.  1.7]
 [5.9 3.2 4.8 1.8]
 [6.1 3.  4.9 1.8]
 [6.  2.2 5.  1.5]
 [6.3 2.7 4.9 1.8]
 [6.3 2.8 5.1 1.5]
 [4.9 2.5 4.5 1.7]
 [6.3 2.5 5.  1.9]
 [5.9 3.  5.1 1.8]
 [6.5 3.2 5.1 2. ]
 [7.2 3.  5.8 1.6]
 [6.  3.  4.8 1.8]]
Vector promedio (no clase): [6.1        2.81904762 4.7952381  1.61428571]
Norma del vector promedio (no clase): 8.411733248018965
Vector del hiperplano (coeficientes): [-0.04627259  0.52114901 -1.00303714 -0.46412669]
Intercepto del hiperplano: 1.452987663388237

-------------------------------------------------------------------------

In [12]:
y_pred = svm.predict(X_test)
y_prob = svm.predict_proba(X_test)

for i, (x, pred, prob) in enumerate(zip(X_test, y_pred, y_prob)):
    projections = [np.dot(x, svm.coef_[j]) + svm.intercept_[j] for j in range(len(iris.target_names))]
    print(f"Vector de prueba {i+1}: {x}")
    print(f"Proyección sobre el hiperplano por clase: {projections}")
    print(f"Probabilidades de pertenencia a cada clase: {prob}")
    print(f"Clasificación final: {iris.target_names[pred]}")
    print("\n" + "="*80 + "\n")

Vector de prueba 1: [5.8 2.8 5.1 2.4]
Proyección sobre el hiperplano por clase: [-3.5855695838740633, -1.4216868858627385, -2.1890962516776318]
Probabilidades de pertenencia a cada clase: [0.010939   0.01005206 0.97900894]
Clasificación final: virginica


Vector de prueba 2: [6.  2.2 4.  1. ]
Proyección sobre el hiperplano por clase: [-2.1543952891124305, -0.5542168842161479, 2.164390242261467]
Probabilidades de pertenencia a cada clase: [0.00878773 0.98168041 0.00953185]
Clasificación final: versicolor


Vector de prueba 3: [5.5 4.2 1.4 0.2]
Proyección sobre el hiperplano por clase: [1.8902369360559947, 1.40160668431112, 10.122885135442065]
Probabilidades de pertenencia a cada clase: [0.98290917 0.00978557 0.00730527]
Clasificación final: setosa


Vector de prueba 4: [7.3 2.9 6.3 1.8]
Proyección sobre el hiperplano por clase: [-4.528032115084597, -1.8755022107982242, -2.3693013956617035]
Probabilidades de pertenencia a cada clase: [0.00307251 0.00674652 0.99018097]
Clasificación final